
name: Integration Test

on: pull_request

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-go@v4
          with:
            go-version: ^1.20
        - uses: actions/setup-node@v4

        - name: Install newman
          run: |
            npm install -g newman

        - name: Dependencies
          run: go mod download -x

        - name: Run tests
          run: |
            go run ./cmd/server/main.go &
            sleep 60
            newman run "cars-api.postman_collection.json" 
          env:
            PORT: 8080
            OTEL_SDK_DISABLED: true
            SERVICE_NAME: "carApi"
